name: ONNX Runtime / Python - ORT Training - Test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

jobs:
  do-the-job:
    if: ${{ (github.event_name == 'workflow_dispatch') || contains( github.event.pull_request.labels.*.name, 'training')}}

    runs-on:
      group: aws-g6-4xlarge-plus

    container:
      image: nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        env:
          TORCH_CUDA_ARCH_LIST: "5.0 6.0 7.0 7.5 8.0 8.6 9.0+PTX"
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
          pip install --no-cache-dir torch-ort onnxruntime-training && python -m torch_ort.configure
          pip install .[tests,onnxruntime-gpu]

      - name: Test with pytest
        working-directory: tests
        run: |
          RUN_SLOW=1 pytest onnxruntime/training/nightly_test_trainer.py --durations=0 -s -vvvv
          RUN_SLOW=1 pytest onnxruntime/training/nightly_test_examples.py --durations=0 -s -vvvv
