name: BetterTransformer / Python - Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    runs-on:
      group: aws-general-8-plus

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (stable)
        run: |
          pip uninstall -y opencv-python
          pip install opencv-python-headless
          pip install --no-cache-dir torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install .[tests]

      - name: Test with pytest (parallel)
        working-directory: tests
        run: |
          pytest bettertransformer --durations=0 -vvvv -s -n auto

      - name: Install dependencies (nightly)
        run: |
          pip uninstall -y torch torchvision torchaudio
          pip install --no-cache-dir --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

      - name: Test with pytest (parallel)
        working-directory: tests
        run: |
          pytest bettertransformer --durations=0 -vvvv -s -n auto
